### ISSUE TITLE
Website landing page

### ISSUE THREAD

**Issue by himanshu007-creator** [RoquesBeach/archipelago#122]
We can improve the background image by making some changes to the scss file.
 
The archipelago image can be clipped, and its size altered.

Suggested changes:
<code>
    background-attachment: fixed;<br>
    background-size: contain;
<br>
</code>

proposed for [this](https://github.com/RoquesBeach/archipelago/blob/1458501352f1f62544baa13de72292f4803f1de0/_sass/minima/custom-styles.scss) file

I would like to work on this issue once it's approved😄

preview

![2021-07-11](https://user-images.githubusercontent.com/65963997/125173490-406f7380-e1dd-11eb-8991-532ad9455d34.png)

**Comment by jbampton** [comment]
Sure sounds great. Sorry for the delay

**Comment by himanshu007-creator** [comment]
issue solved by #139
