### ISSUE TITLE
Cloudflare Authorization Error

### ISSUE THREAD

**Issue by ayushrana182** [RoquesBeach/archipelago#182]
![Capture_LI](https://user-images.githubusercontent.com/43984189/153385860-ef3bdcd2-42f2-47de-84a1-bf8703b7032e.jpg)

^^ This is the behavior when you try to test it locally. This is the error message generated from the link 

```
{
success: false,
errors: [
{
code: 9106,
message: "Missing X-Auth-Key, X-Auth-Email or Authorization headers"
}
]
}
```

**Comment by jbampton** [comment]
The new way:

` wrangler dev --local` 👍
